apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: northernjay-com-tls
spec:
  secretName: northernjay-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: northernjay.com
  dnsNames:
    - northernjay.com
    - www.northernjay.com
